### ISSUE TITLE
WriteTeX2 does not work on inkscape 1.2.1

### ISSUE THREAD

**Issue by joaochenriques** [wanglongqi/WriteTeX2#2]
This is a fantastic plugin for inkscape. However it does not work in the latest version of inkscape.
Can you please check this issue?

**Comment by wanglongqi** [comment]
@joaochenriques can you try a possible solution from https://github.com/wanglongqi/WriteTeX/issues/28#issuecomment-1279594439. and let us know the outcome. Thanks!

**Comment by joaochenriques** [comment]
It worked! For me this is the most useful plugin for Inkscape. Thank you very much.
